import "./globals.css";

export const metadata = {
  title: "MBN Finances",
  description: "Generated by create next app",
};

export default function ({ children }) {
  return (  
    <html lang="en">
      <body className="text-[#cccccc] overflow-x-hidden" >
        {children}
      </body>
    </html>
  );
}
